#!/usr/bin/env bun

import { parse, type Node } from "@bgotink/kdl/v1-compat";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dir, "..");
const configPath = resolve(
  repositoryRoot,
  "nix/shared/features/niri/config.kdl",
);
const outputPath = resolve(
  repositoryRoot,
  "nix/shared/features/niri/README.md",
);
const checkOnly = Bun.argv.slice(2).includes("--check");

type Keybinding = {
  action: string;
  section: string;
  shortcut: string;
};

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|");
}

function formatShortcut(shortcut: string): string {
  return shortcut.replaceAll("+", " + ");
}

function formatAction(action: Node): string {
  const actionName = action.getName();
  const actionArguments = action.getArguments().join(" ");

  if (actionName === "spawn") {
    return `Run \`${actionArguments}\``;
  }

  const actionLabel = actionName.replaceAll("-", " ");

  return `${actionLabel.charAt(0).toUpperCase()}${actionLabel.slice(1)}${
    actionArguments ? ` ${actionArguments}` : ""
  }`;
}

function renderTable(keybindings: Keybinding[]): string {
  const rows = [
    ["Shortcut", "Action"],
    ...keybindings.map((keybinding) => [
      formatShortcut(keybinding.shortcut),
      escapeMarkdown(keybinding.action),
    ]),
  ];
  const columnWidths = rows[0].map((_, columnIndex) =>
    Math.max(...rows.map((row) => row[columnIndex].length)),
  );
  const renderRow = (row: string[]) =>
    `| ${row.map((cell, index) => cell.padEnd(columnWidths[index])).join(" | ")} |`;

  return [
    renderRow(rows[0]),
    renderRow(columnWidths.map((width) => "-".repeat(width))),
    ...rows.slice(1).map(renderRow),
  ].join("\n");
}

function getSection(binding: Node): string | undefined {
  const comments = binding.leading?.matchAll(/^\s*\/\/\s*(.+?)\s*$/gm);
  return comments ? [...comments].at(-1)?.[1] : undefined;
}

function readKeybindings(config: string): Keybinding[] {
  const bindBlock = parse(config).findNodeByName("binds");

  if (!bindBlock?.children) {
    throw new Error(`Could not find binds {} in ${configPath}`);
  }

  const keybindings: Keybinding[] = [];
  let section = "Other";

  for (const binding of bindBlock.children.nodes) {
    section = getSection(binding) ?? section;
    const actionNodes = binding.children?.nodes ?? [];

    if (actionNodes.length !== 1) {
      throw new Error(
        `Expected one action for ${binding.getName()} in ${configPath}`,
      );
    }

    const title = binding.getProperty("hotkey-overlay-title");
    keybindings.push({
      action: typeof title === "string" ? title : formatAction(actionNodes[0]),
      section,
      shortcut: binding.getName(),
    });
  }

  return keybindings;
}

function renderReference(keybindings: Keybinding[]): string {
  const sections = Map.groupBy(keybindings, (keybinding) => keybinding.section);
  const renderedSections = [...sections].map(
    ([section, sectionKeybindings]) => {
      return `## ${section}\n\n${renderTable(sectionKeybindings)}`;
    },
  );

  return `<!-- This file is generated by scripts/generate-niri-keybindings.ts. Do not edit it directly. -->

# Niri keyboard reference

\`Mod\` is Super in a normal Niri session and Alt when Niri runs in a nested window.

${renderedSections.join("\n\n")}`;
}

const reference = `${renderReference(readKeybindings(await Bun.file(configPath).text()))}\n`;
const existingReference = await Bun.file(outputPath)
  .text()
  .catch(() => undefined);

if (checkOnly) {
  if (reference !== existingReference) {
    console.error(
      `${outputPath} is stale. Run bun scripts/generate-niri-keybindings.ts.`,
    );
    process.exit(1);
  }
} else {
  await Bun.write(outputPath, reference);
}
